name: CI Build and Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Запускаем на виртуальной машине с Ubuntu
    runs-on: ubuntu-latest
    
    container:
      image: maven:3.9.11-eclipse-temurin-21-noble
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Ensure mvnw is executable
        run: |
          if [ -f "./mvnw" ]; then
            chmod +x ./mvnw
          fi
      
      - name: Build with Maven
        run: |
          if [ -f "./mvnw" ]; then
            ./mvnw clean package
          else
            mvn clean package
          fi
      
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: ./target/*.jar
          retention-days: 7